import type { CardToken, ProviderOrderEvidence } from "./contracts";
export type MercadoPagoOrderRequest = { idempotencyKey: string; externalReference: string; total: number; currency: "ARS"; payerEmail: string; card: CardToken };
export type MercadoPagoOrdersGateway = { createOrder(request: MercadoPagoOrderRequest): Promise<ProviderOrderEvidence>; getOrder(providerOrderId: string): Promise<ProviderOrderEvidence | undefined> };
type Fetch = (input: string, init: RequestInit) => Promise<Response>;
export function createMercadoPagoOrdersGateway({ accessToken, fetch = globalThis.fetch }: { accessToken: string; fetch?: Fetch }): MercadoPagoOrdersGateway {
  if (!accessToken) throw new Error("MERCADO_PAGO_ACCESS_TOKEN is required.");
  return {
    async createOrder(request) { const response = await fetch("https://api.mercadopago.com/v1/orders", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${accessToken}`, "X-Idempotency-Key": request.idempotencyKey }, body: JSON.stringify({ type: "online", external_reference: request.externalReference, total_amount: String(request.total), processing_mode: "automatic", capture_mode: "automatic", payer: { email: request.payerEmail }, transactions: { payments: [{ amount: String(request.total), payment_method: { id: request.card.paymentMethodId, type: request.card.paymentType, token: request.card.cardToken, installments: request.card.installments, ...(request.card.issuerId ? { issuer_id: request.card.issuerId } : {}) } }] }, config: { online: { transaction_security: { validation: "on_fraud_risk", liability_shift: "required" } } } }) }); return parseOrder(response); },
    async getOrder(providerOrderId) { const response = await fetch(`https://api.mercadopago.com/v1/orders/${encodeURIComponent(providerOrderId)}`, { method: "GET", headers: { Authorization: `Bearer ${accessToken}` } }); if (response.status === 404) return undefined; return parseOrder(response); },
  };
}
async function parseOrder(response: Response): Promise<ProviderOrderEvidence> { const body = await response.json().catch(() => ({})) as Record<string, unknown>; if (!response.ok) throw new Error(`MERCADO_PAGO_ORDER_${response.status}`); const payments = body.transactions && typeof body.transactions === "object" ? (body.transactions as { payments?: unknown }).payments : undefined; const payment = Array.isArray(payments) ? payments[0] : undefined; if (typeof body.id !== "string" || typeof body.external_reference !== "string" || typeof body.status !== "string" || typeof body.status_detail !== "string" || typeof body.last_updated_date !== "string" || !payment || typeof payment !== "object") throw new Error("MERCADO_PAGO_ORDER_INVALID_RESPONSE"); const p = payment as Record<string, unknown>; if (typeof p.id !== "string" || typeof p.status !== "string" || typeof p.status_detail !== "string") throw new Error("MERCADO_PAGO_ORDER_INVALID_RESPONSE"); return { id: body.id, externalReference: body.external_reference, status: body.status, statusDetail: body.status_detail, updatedAt: body.last_updated_date, payment: { id: p.id, status: p.status, statusDetail: p.status_detail } }; }
