import type { Brand, Category, Product } from "@/lib/catalog/types";

const createdAt = "2026-06-14T00:00:00.000Z";
const updatedAt = createdAt;

export const categories: Category[] = [
  {
    id: "cat-botines",
    name: "Botines",
    slug: "botines",
    description: "Calzado preparado para dominar distintos tipos de cancha.",
    imageUrl: "/catalog/categories/botines.png",
    parentId: null,
    isActive: true,
  },
  {
    id: "cat-camisetas",
    name: "Camisetas",
    slug: "camisetas",
    description: "Camisetas de fútbol con identidad de club y entrenamiento.",
    imageUrl: "/catalog/categories/camisetas.png",
    parentId: null,
    isActive: true,
  },
  {
    id: "cat-entrenamiento",
    name: "Entrenamiento",
    slug: "entrenamiento",
    description: "Indumentaria técnica para sesiones, pretemporada y día a día.",
    imageUrl: "/catalog/categories/entrenamiento.png",
    parentId: null,
    isActive: true,
  },
  {
    id: "cat-accesorios",
    name: "Accesorios",
    slug: "accesorios",
    description: "Complementos para completar el bolso de partido.",
    imageUrl: "/catalog/categories/accesorios.png",
    parentId: null,
    isActive: true,
  },
];

export const brands: Brand[] = [
  {
    id: "brand-verde-arena",
    name: "Verde Arena",
    slug: "verde-arena",
    description: "Marca propia inspirada en fútbol amateur, barrio y cancha chica.",
    logoUrl: null,
    isActive: true,
    createdAt,
    updatedAt,
  },
  {
    id: "brand-northline",
    name: "Northline",
    slug: "northline",
    description: "Equipamiento técnico ficticio para entrenamiento intenso.",
    logoUrl: null,
    isActive: true,
    createdAt,
    updatedAt,
  },
  {
    id: "brand-arena-control",
    name: "Arena Control",
    slug: "arena-control",
    description: "Productos ficticios centrados en control, precisión y ritmo de juego.",
    logoUrl: null,
    isActive: true,
    createdAt,
    updatedAt,
  },
  {
    id: "brand-matchday-studio",
    name: "Matchday Studio",
    slug: "matchday-studio",
    description: "Diseño editorial ficticio para camisetas y accesorios de partido.",
    logoUrl: null,
    isActive: true,
    createdAt,
    updatedAt,
  },
  {
    id: "brand-terreno",
    name: "Terreno",
    slug: "terreno",
    description: "Línea ficticia preparada para superficies, barro y potrero.",
    logoUrl: null,
    isActive: true,
    createdAt,
    updatedAt,
  },
];

export const products: Product[] = [
  {
    id: "prod-control-fg-verde",
    name: "Control FG Verde",
    slug: "control-fg-verde",
    description: "Botín firme para cancha natural con calce estable y toque preciso.",
    categoryId: "cat-botines",
    categorySlug: "botines",
    brandId: "brand-arena-control",
    brandSlug: "arena-control",
    price: 112000,
    compareAtPrice: 132000,
    currency: "ARS",
    featured: true,
    status: "published",
    isActive: true,
    images: [
      {
        id: "img-control-fg-verde-main",
        productId: "prod-control-fg-verde",
        variantId: null,
        url: "/catalog/products/control-fg-verde-1.png",
        alt: "Botines Control FG Verde vista lateral",
        position: 1,
        isPrimary: true,
        createdAt,
        updatedAt,
      },
      {
        id: "img-control-fg-verde-detail",
        productId: "prod-control-fg-verde",
        variantId: null,
        url: "/catalog/products/control-fg-verde-2.png",
        alt: "Detalle de suela FG de botines Control Verde",
        position: 2,
        isPrimary: false,
        createdAt,
        updatedAt,
      },
    ],
    variants: [
      {
        id: "var-control-fg-verde-40",
        productId: "prod-control-fg-verde",
        name: "Verde / 40 / FG",
        size: "40",
        color: "Verde",
        surface: "FG",
        stock: 4,
        price: null,
        sku: "AC-FG-VER-40",
        isActive: true,
      },
      {
        id: "var-control-fg-verde-41",
        productId: "prod-control-fg-verde",
        name: "Verde / 41 / FG",
        size: "41",
        color: "Verde",
        surface: "FG",
        stock: 2,
        price: 115000,
        sku: "AC-FG-VER-41",
        isActive: true,
      },
    ],
    createdAt,
    updatedAt,
  },
  {
    id: "prod-terreno-tf-arena",
    name: "Terreno TF Arena",
    slug: "terreno-tf-arena",
    description: "Botín para sintético con tracción corta y perfil resistente.",
    categoryId: "cat-botines",
    categorySlug: "botines",
    brandId: "brand-terreno",
    brandSlug: "terreno",
    price: 98000,
    compareAtPrice: null,
    currency: "ARS",
    featured: false,
    status: "published",
    isActive: true,
    images: [
      {
        id: "img-terreno-tf-arena-main",
        productId: "prod-terreno-tf-arena",
        variantId: null,
        url: "/catalog/products/terreno-tf-arena-1.png",
        alt: "Botines Terreno TF Arena color arena",
        position: 1,
        isPrimary: true,
        createdAt,
        updatedAt,
      },
    ],
    variants: [
      {
        id: "var-terreno-tf-arena-39",
        productId: "prod-terreno-tf-arena",
        name: "Arena / 39 / TF",
        size: "39",
        color: "Arena",
        surface: "TF",
        stock: 3,
        price: null,
        sku: "TE-TF-ARE-39",
        isActive: true,
      },
      {
        id: "var-terreno-tf-arena-42",
        productId: "prod-terreno-tf-arena",
        name: "Arena / 42 / TF",
        size: "42",
        color: "Arena",
        surface: "TF",
        stock: 0,
        price: null,
        sku: "TE-TF-ARE-42",
        isActive: true,
      },
    ],
    createdAt,
    updatedAt,
  },
  {
    id: "prod-camiseta-verde-arena-local",
    name: "Camiseta Verde Arena Local",
    slug: "camiseta-verde-arena-local",
    description: "Camiseta titular ficticia con textura liviana y corte regular.",
    categoryId: "cat-camisetas",
    categorySlug: "camisetas",
    brandId: "brand-verde-arena",
    brandSlug: "verde-arena",
    price: 62000,
    compareAtPrice: 74000,
    currency: "ARS",
    featured: true,
    status: "published",
    isActive: true,
    images: [
      {
        id: "img-camiseta-verde-local-main",
        productId: "prod-camiseta-verde-arena-local",
        variantId: null,
        url: "/catalog/products/camiseta-verde-arena-local-1.png",
        alt: "Camiseta Verde Arena local frente",
        position: 1,
        isPrimary: true,
        createdAt,
        updatedAt,
      },
      {
        id: "img-camiseta-verde-local-back",
        productId: "prod-camiseta-verde-arena-local",
        variantId: null,
        url: "/catalog/products/camiseta-verde-arena-local-2.png",
        alt: "Camiseta Verde Arena local espalda",
        position: 2,
        isPrimary: false,
        createdAt,
        updatedAt,
      },
    ],
    variants: [
      {
        id: "var-camiseta-verde-s",
        productId: "prod-camiseta-verde-arena-local",
        name: "Verde / S",
        size: "S",
        color: "Verde",
        surface: null,
        stock: 6,
        price: null,
        sku: "VA-CAM-LOC-S",
        isActive: true,
      },
      {
        id: "var-camiseta-verde-m",
        productId: "prod-camiseta-verde-arena-local",
        name: "Verde / M",
        size: "M",
        color: "Verde",
        surface: null,
        stock: 8,
        price: null,
        sku: "VA-CAM-LOC-M",
        isActive: true,
      },
      {
        id: "var-camiseta-verde-l",
        productId: "prod-camiseta-verde-arena-local",
        name: "Verde / L",
        size: "L",
        color: "Verde",
        surface: null,
        stock: 5,
        price: null,
        sku: "VA-CAM-LOC-L",
        isActive: true,
      },
    ],
    createdAt,
    updatedAt,
  },
  {
    id: "prod-camiseta-matchday-negra",
    name: "Camiseta Matchday Negra",
    slug: "camiseta-matchday-negra",
    description: "Camiseta alternativa ficticia con estética nocturna de partido.",
    categoryId: "cat-camisetas",
    categorySlug: "camisetas",
    brandId: "brand-matchday-studio",
    brandSlug: "matchday-studio",
    price: 58000,
    compareAtPrice: null,
    currency: "ARS",
    featured: false,
    status: "published",
    isActive: true,
    images: [
      {
        id: "img-camiseta-matchday-negra-main",
        productId: "prod-camiseta-matchday-negra",
        variantId: null,
        url: "/catalog/products/camiseta-matchday-negra-1.png",
        alt: "Camiseta Matchday negra frente",
        position: 1,
        isPrimary: true,
        createdAt,
        updatedAt,
      },
    ],
    variants: [
      {
        id: "var-matchday-negra-m",
        productId: "prod-camiseta-matchday-negra",
        name: "Negro / M",
        size: "M",
        color: "Negro",
        surface: null,
        stock: 7,
        price: null,
        sku: "MS-CAM-NEG-M",
        isActive: true,
      },
      {
        id: "var-matchday-negra-xl",
        productId: "prod-camiseta-matchday-negra",
        name: "Negro / XL",
        size: "XL",
        color: "Negro",
        surface: null,
        stock: 2,
        price: null,
        sku: "MS-CAM-NEG-XL",
        isActive: true,
      },
    ],
    createdAt,
    updatedAt,
  },
  {
    id: "prod-training-northline-jacket",
    name: "Campera Northline Training",
    slug: "campera-northline-training",
    description: "Campera liviana para entrada en calor, traslado y banco.",
    categoryId: "cat-entrenamiento",
    categorySlug: "entrenamiento",
    brandId: "brand-northline",
    brandSlug: "northline",
    price: 89000,
    compareAtPrice: 99000,
    currency: "ARS",
    featured: true,
    status: "published",
    isActive: true,
    images: [
      {
        id: "img-northline-jacket-main",
        productId: "prod-training-northline-jacket",
        variantId: null,
        url: "/catalog/products/northline-training-jacket-1.png",
        alt: "Campera Northline Training verde oscuro",
        position: 1,
        isPrimary: true,
        createdAt,
        updatedAt,
      },
    ],
    variants: [
      {
        id: "var-northline-jacket-m",
        productId: "prod-training-northline-jacket",
        name: "Verde oscuro / M",
        size: "M",
        color: "Verde oscuro",
        surface: null,
        stock: 4,
        price: null,
        sku: "NL-JAC-VER-M",
        isActive: true,
      },
      {
        id: "var-northline-jacket-l",
        productId: "prod-training-northline-jacket",
        name: "Verde oscuro / L",
        size: "L",
        color: "Verde oscuro",
        surface: null,
        stock: 4,
        price: null,
        sku: "NL-JAC-VER-L",
        isActive: true,
      },
    ],
    createdAt,
    updatedAt,
  },
  {
    id: "prod-conos-terreno-pack",
    name: "Pack Conos Terreno",
    slug: "pack-conos-terreno",
    description: "Set de conos flexibles para coordinación, velocidad y ejercicios técnicos.",
    categoryId: "cat-accesorios",
    categorySlug: "accesorios",
    brandId: "brand-terreno",
    brandSlug: "terreno",
    price: 24000,
    compareAtPrice: null,
    currency: "ARS",
    featured: false,
    status: "published",
    isActive: true,
    images: [
      {
        id: "img-conos-terreno-main",
        productId: "prod-conos-terreno-pack",
        variantId: null,
        url: "/catalog/products/conos-terreno-pack-1.png",
        alt: "Pack de conos Terreno color naranja",
        position: 1,
        isPrimary: true,
        createdAt,
        updatedAt,
      },
    ],
    variants: [
      {
        id: "var-conos-naranja-unico",
        productId: "prod-conos-terreno-pack",
        name: "Naranja / Único",
        size: "Único",
        color: "Naranja",
        surface: null,
        stock: 12,
        price: null,
        sku: "TE-CON-NAR-U",
        isActive: true,
      },
    ],
    createdAt,
    updatedAt,
  },
  {
    id: "prod-botella-matchday",
    name: "Botella Matchday Studio",
    slug: "botella-matchday-studio",
    description: "Botella deportiva ficticia para entrenamiento y partido.",
    categoryId: "cat-accesorios",
    categorySlug: "accesorios",
    brandId: "brand-matchday-studio",
    brandSlug: "matchday-studio",
    price: 18000,
    compareAtPrice: 22000,
    currency: "ARS",
    featured: true,
    status: "published",
    isActive: true,
    images: [
      {
        id: "img-botella-matchday-main",
        productId: "prod-botella-matchday",
        variantId: null,
        url: "/catalog/products/botella-matchday-1.png",
        alt: "Botella deportiva Matchday Studio color humo",
        position: 1,
        isPrimary: true,
        createdAt,
        updatedAt,
      },
    ],
    variants: [
      {
        id: "var-botella-humo-unico",
        productId: "prod-botella-matchday",
        name: "Humo / Único",
        size: "Único",
        color: "Humo",
        surface: null,
        stock: 10,
        price: null,
        sku: "MS-BOT-HUM-U",
        isActive: true,
      },
    ],
    createdAt,
    updatedAt,
  },
  {
    id: "prod-legacy-archived",
    name: "Producto Archivado Demo",
    slug: "producto-archivado-demo",
    description: "Producto mock usado para validar exclusión pública.",
    categoryId: "cat-entrenamiento",
    categorySlug: "entrenamiento",
    brandId: "brand-verde-arena",
    brandSlug: "verde-arena",
    price: 50000,
    compareAtPrice: null,
    currency: "ARS",
    featured: false,
    status: "archived",
    isActive: false,
    images: [
      {
        id: "img-legacy-archived-main",
        productId: "prod-legacy-archived",
        variantId: null,
        url: "/catalog/products/legacy-archived-1.jpg",
        alt: "Producto archivado de demostración",
        position: 1,
        isPrimary: true,
        createdAt,
        updatedAt,
      },
    ],
    variants: [
      {
        id: "var-legacy-archived-unico",
        productId: "prod-legacy-archived",
        name: "Demo / Único",
        size: "Único",
        color: "Demo",
        surface: null,
        stock: 0,
        price: null,
        sku: "VA-LEG-DEMO-U",
        isActive: false,
      },
    ],
    createdAt,
    updatedAt,
  },
];
